Network:
  epochs: 500
  batch_size: 50
  n_steps: 12
  dataset: "CIFAR10"
  data_path: "../../datasets/cifar10"
  # data_path: "../../../../datasets/cifar10"
  log_path: "logs/cifar10"
  backend: "cuda"
  optimizer: "SGD"
  lr: 0.05
  weight_decay: 0.0005
  loss: "count"
  norm_grad: 0
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 10
  desired_count: 10
  undesired_count: 1
  tau_m: 7
  tau_s: 4
  tau_grad: 3.5

Layers:
  conv_1:
    type: "conv"   # 32*32
    in_channels: 3
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  conv_2:
    type: "conv" # 32*32
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
  
  dropout_1:
    type: "dropout"
    p: 0.1

  conv_3:
    type: "conv" # 16*16
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  conv_4:
    type: "conv"  # 16*16
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  conv_5:
    type: "conv" # 16*16
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2
  
  dropout_2:
    type: "dropout"
    p: 0.1

  conv_6:
    type: "conv"  # 8*8
    in_channels: 256
    out_channels: 512
    kernel_size: 3
    padding: 1
    threshold: 1

  conv_7:
    type: "conv"  # 8*8
    in_channels: 512
    out_channels: 512
    kernel_size: 3
    padding: 1
    threshold: 1
  
  conv_8:
    type: "conv"  # 8*8
    in_channels: 512
    out_channels: 512
    kernel_size: 3
    padding: 1
    threshold: 1
  
  pooling_3:
    type: "pooling"
    kernel_size: 2
  
  dropout_3:
    type: "dropout"
    p: 0.1

  FC_1:
    type: "linear"
    n_inputs: 8192
    n_outputs: 2048
    threshold: 1
    
  dropout_4:
    type: "dropout"
    p: 0.1

  FC_2:
    type: "linear"
    n_inputs: 2048
    n_outputs: 2048
    threshold: 1
  
  dropout_5:
    type: "dropout"
    p: 0.1

  output:
    type: "linear"
    n_inputs: 2048
    n_outputs: 10
    threshold: 1

