Network:
  epochs: 800
  batch_size: 16
  n_steps: 20
  dataset: "CIFAR10DVS"
  #data_path: "../../datasets/cifar10_dvs"
  data_path: "../../../../datasets/cifar10_dvs"
  log_path: "logs/cifar10_dvs"
  backend: "cuda"
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.0005
  loss: "count"
  norm_grad: 0.1
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 10
  desired_count: 10
  undesired_count: 1
  tau_m: 8
  tau_s: 4.5
  tau_grad: 4
  max_dudt_inv: 123456789

Layers:
  conv_1:
    type: "conv"   # 48*48
    in_channels: 2
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
  
  dropout_1:
    type: "dropout"
    p: 0.05

  conv_2:
    type: "conv" # 24*24
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  dropout_2:
    type: "dropout"
    p: 0.05

  conv_3:
    type: "conv" # 24*24
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_3:
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  dropout_3:
    type: "dropout"
    p: 0.05

  conv_4:
    type: "conv"  # 12*12
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1
 
  dropout_4:
    type: "dropout"
    p: 0.05

  conv_5:
    type: "conv" # 12*12
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1
  
  pooling_5:
    type: "pooling"
    kernel_size: 2

  dropout_5:
    type: "dropout"
    p: 0.05
  
  conv_6:
    type: "conv" # 6*6
    in_channels: 256
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1
  
  pooling_6:
    type: "pooling"
    kernel_size: 2

  dropout_6:
    type: "dropout"
    p: 0.05

  FC_1:
    type: "linear"
    n_inputs: 1152
    n_outputs: 512
    threshold: 1

  dropout_7:
    type: "dropout"
    p: 0.05

  FC_2:
    type: "linear"
    n_inputs: 512
    n_outputs: 512
    threshold: 1
  
  dropout_8:
    type: "dropout"
    p: 0.05

  output:
    type: "linear"
    n_inputs: 512
    n_outputs: 10
    threshold: 1