Network:
  epochs: 1000
  batch_size: 8
  n_steps: 20
  t_train: 14
  dataset: "DVS128Gesture"
  data_path: "../../datasets/dvs128_gesture"
  # data_path: "../../../../datasets/dvs128_gesture"
  log_path: "logs/dvs128_gesture"
  backend: "cuda"
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.0005
  loss: "count"
  norm_grad: 1
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 11
  desired_count: 7
  undesired_count: 1
  tau_m: 7.5
  tau_s: 4
  tau_grad: 3.5
  max_dudt_inv: 123456789

Layers:
  conv_1:
    type: "conv"   # 128*128
    in_channels: 2
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
  
  dropout_1:
    type: "dropout"
    p: 0.1

  conv_2:
    type: "conv" # 64*64
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2

  dropout_2:
    type: "dropout"
    p: 0.1

  conv_3:
    type: "conv" # 32*32
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_3:
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  dropout_3:
    type: "dropout"
    p: 0.1

  conv_4:
    type: "conv"  # 16*16
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_4:
    type: "pooling"
    kernel_size: 2
 
  dropout_4:
    type: "dropout"
    p: 0.1

  conv_5:
    type: "conv" # 8*8
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1
  
  pooling_5:
    type: "pooling"
    kernel_size: 2

  dropout_5:
    type: "dropout"
    p: 0.1
  
  conv_6:
    type: "conv" # 4*4
    in_channels: 128
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1
  
  pooling_6:
    type: "pooling"
    kernel_size: 2

  dropout_6:
    type: "dropout"
    p: 0.1

  FC_1:
    type: "linear"
    n_inputs: 512
    n_outputs: 512
    threshold: 1

  dropout_7:
    type: "dropout"
    p: 0.1

  FC_2:
    type: "linear"
    n_inputs: 512
    n_outputs: 128
    threshold: 1
  
  dropout_8:
    type: "dropout"
    p: 0.1

  output:
    type: "linear"
    n_inputs: 128
    n_outputs: 11
    threshold: 1