Network:
  epochs: 150
  batch_size: 50
  n_steps: 5
  dataset: "FashionMNIST"
  # data_path: "../../datasets/FashionMNIST"
  data_path: "../../../../datasets/FashionMNIST"
  log_path: "logs/FashionMNIST"
  backend: "cuda"
  optimizer: "AdamW"
  lr: 0.0005
  weight_decay: 0.0005
  avg_spike_init: 0.5
  loss: "count"
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 10
  desired_count: 5
  undesired_count: 1
  tau_m: 5
  tau_s: 3
  tau_grad: 2.5

Layers:
  conv_1:
    type: "conv"
    in_channels: 1
    out_channels: 32
    kernel_size: 5
    padding: 2
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2

  conv_2:
    type: "conv"
    in_channels: 32
    out_channels: 64
    kernel_size: 5
    padding: 2
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2

  FC_1:
    type: "linear"
    n_inputs: 3136
    n_outputs: 1024
    threshold: 1

  output:
    type: "linear"
    n_inputs: 1024
    n_outputs: 10
    threshold: 1
