Network:
  epochs: 100
  batch_size: 50
  n_steps: 5
  dataset: "MNIST"
  data_path: "../../datasets/mnist"
  # data_path: "../../../../datasets/mnist"
  log_path: "logs/mnist"
  backend: "cuda"
  optimizer: "AdamW"
  lr: 0.0005
  weight_decay: 0.0005
  avg_spike_init: 0.5
  loss: "count"
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 10
  desired_count: 5
  undesired_count: 1
  tau_m: 5
  tau_s: 3
  tau_grad: 2.5
  max_dudt_inv: 123456789

Layers:
  conv_1:
    type: "conv"
    in_channels: 1
    out_channels: 15
    kernel_size: 5
    padding: 0
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
    threshold: 1

  conv_2:
    type: "conv"
    in_channels: 15
    out_channels: 40
    kernel_size: 5
    padding: 0
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2
    threshold: 1

  FC_1:
    type: "linear"
    n_inputs: 640
    n_outputs: 300
    threshold: 1

  output:
    type: "linear"
    n_inputs: 300
    n_outputs: 10
    weight_scale: 1
    threshold: 1