Network:
  epochs: 100
  batch_size: 50
  n_steps: 5
  dataset: "MNIST"
  data_path: "../../../../datasets/mnist"
  log_path: "logs/mnist_original"
  lr: 0.0005
  optimizer: "AdamW"
  loss: "count"
  max_dudt_inv: 123456789
  gradient_type: "original"
  n_class: 10
  desired_count: 5
  undesired_count: 0
  tau_m: 5
  tau_s: 3

Layers:
  FC_1:
    type: "linear"
    n_inputs: 784
    n_outputs: 300
    weight_scale: 1
    threshold: 1

  FC_2:
    type: "linear"
    n_inputs: 300
    n_outputs: 300
    weight_scale: 1
    threshold: 1

  output:
    type: "linear"
    n_inputs: 300
    n_outputs: 10
    weight_scale: 1
    threshold: 1