Network:
  epochs: 120
  batch_size: 50
  n_steps: 30
  dataset: "NMNIST"
  data_path: "../../datasets/n_mnist"
  # data_path: "../../../../datasets/n_mnist"
  log_path: "logs/n-mnist"
  backend: "cuda"
  optimizer: "AdamW"
  lr: 0.0005
  weight_decay: 0.2
  avg_spike_init: 2
  loss: "count"
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 10
  desired_count: 15
  undesired_count: 2
  tau_m: 8
  tau_s: 4
  tau_grad: 3

Layers:
  conv_1:
    type: "conv" # 32
    in_channels: 2
    out_channels: 12
    kernel_size: 5
    padding: 1
    threshold: 1

  pooling_1:  # 16
    type: "pooling"
    kernel_size: 2

  conv_2: # 12
    type: "conv"
    in_channels: 12
    out_channels: 64
    kernel_size: 5
    padding: 0
    threshold: 1

  pooling_2: # 6
    type: "pooling"
    kernel_size: 2

  output:
    type: "linear"
    n_inputs: 2304
    n_outputs: 10
    threshold: 1

