Network:
  epochs: 500
  batch_size: 50
  n_steps: 16
  dataset: "CIFAR10"
  data_path: "../../datasets/cifar10"
  # data_path: "../../../../datasets/cifar10"
  log_path: "logs/cifar10"
  backend: "cuda"
  optimizer: "Adam"
  lr: 0.0002
  weight_decay: 0.0005
  loss: "count"
  norm_grad: 0
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 10
  desired_count: 12
  undesired_count: 1
  tau_m: 7
  tau_s: 4
  tau_grad: 3.5
  max_dudt_inv: 123456789
  
  model_import: "networks.resnet"